### ISSUE TITLE
Opine can't find template views on Deno Deploy

### ISSUE THREAD

**Issue by michaellindstromm** [cmorten/opine#168]
# Opine can't find template views on Deno Deploy

Setup:

- Deno Version: 1.22.3
- v8 Version: 
- Typescript Version: 
- Opine Version: 2.2

## Details
repo: https://github.com/michaellindstromm/tech-stack-template
deno deploy url: https://michaellindstromm-tst.deno.dev/

Trying to just setup a boilerplate with some different tech I have wanted to try. I have tried a number of different ways, but can't seem to get this to work, so I just started over and took the boilerplate from the opine-cli using eta as a templating engine. Everything works fine on local running `deno run --allow-net --allow-read --allow-env mod.ts`

Deno deploy gets error though.

> `Error: Failed to lookup view "error" in views directory "/src/views"
    at Function.render (https://deno.land/x/opine@2.2.0/src/application.ts:398:25)
    at Response.render (https://deno.land/x/opine@2.2.0/src/response.ts:466:13)
    at errorHandler (file:///src/app.ts:29:9)
    at Layer1.handle_error (https://deno.land/x/opine@2.2.0/src/router/layer.ts:30:15)
    at trim_prefix (https://deno.land/x/opine@2.2.0/src/router/index.ts:221:19)
    at https://deno.land/x/opine@2.2.0/src/router/index.ts:198:13
    at Function.process_params (https://deno.land/x/opine@2.2.0/src/router/index.ts:236:16)
    at next (https://deno.land/x/opine@2.2.0/src/router/index.ts:191:14)
    at Layer1.handle_error (https://deno.land/x/opine@2.2.0/src/router/layer.ts:27:16)
    at trim_prefix (https://deno.land/x/opine@2.2.0/src/router/index.ts:221:19)`

Not sure where to go next? Help?

**Comment by michaellindstromm** [comment]
Oh I found it, Deno Deploy does not support Deno.statSync. Any reason to use statSync over a Deno Deploy supported fs api method?

https://github.com/cmorten/opine/blob/07f563a3884b1575e45cfc015bc4cbfe77ae95e3/src/view.ts#L19
https://deno.com/deploy/docs/runtime-fs

**Comment by cmorten** [comment]
> Oh I found it, Deno Deploy does not support Deno.statSync. Any reason to use statSync over a Deno Deploy supported fs api method?
> 
> https://github.com/cmorten/opine/blob/07f563a3884b1575e45cfc015bc4cbfe77ae95e3/src/view.ts#L19
> 
> 
> https://deno.com/deploy/docs/runtime-fs

Ah good find - most likely because this code predates Deno Deploy IIRC 😅

Suspect the code could be updated to be async using `Deno.stat` but would need to have more of an explore. PRs very welcome if want to give it a go!

**Comment by cmorten** [comment]
Have updating to use `Deno.stat()` in https://github.com/cmorten/opine/releases/tag/2.3.2

Hopefully this resolves the issue.
